language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'stable' 
  - 'iojs-v1.3'
  - 'iojs'

sudo: false

before_install:
  - npm install -g npm@latest
  - npm install -g grunt-cli
install:
  - npm install

